Feature/smart block brands
Source-Digital/marketplace-admin pull request #69
Opened 2021-02-10 13:39 UTC by sunil2342

- Added smartblock-brand
- Added map component for location search

2021-02-10 14:53 UTC, sonokoh requested changes
May I ask one favor? Would you extract smartblock component itself into a separate component? When we distribute smartblock components we don't need editor part.

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +    fields () {
Since this data is constant (not reactive) the intent is clearer if we use lifecycle hooks to create instant property. Also it won't be watched by vue system

```
created() {
  this.fields = [...]
}
```

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +      this.details = clonedeep(this.defaultSchema)
I believe the reset behavior of the other blocks is it resets to the last saved state. Can you dblcheck and make it consistent?

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +        this.$ee.templates.html.escape(this.settings.description)
Can we just use $sanitize here to sanitize for consistency?
Also is this description supposed to be a markdown format?

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +                  style="width:100%; 'margin-top': 10"
```suggestion
                  style="width:100%; margin-top: 10px;"
```

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +                  :rules="field.required ? [val => !!val || 'Required *'] : []"
```suggestion
                  :rules="field.required ? [$rules.required] : []"
```

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +                  v-if="Number.isInteger(settings.video.src)"
These are bit naive way to distinguish video types. We should ask for video src type (=youtube|vimeo|url) and then ask for id/url

2021-02-10 14:53 UTC, sonokoh commented on src/components/Maps.vue
> +      default: () => ({ lat: -34.397, lng: 150.644 })
Can we have no default?

2021-02-10 14:53 UTC, sonokoh commented on src/components/Maps.vue
> +      apiKey: this.$store.state.system.api.gmaps_key
We need to keep in mind that smartblock components will run in experience engine -- can we make api key a prop of Maps component and provide api key via db through settings or relevant fields?

2021-02-10 14:53 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +          <template v-if="details.image.src.includes('maps/embed')">
this is also bit naive as well. Do we have better way of distinguishing map url? perhaps create separate field?

2021-02-11 12:56 UTC, sunil2342 commented on src/components/SmartBlocks/Brand.vue
> +        this.$ee.templates.html.escape(this.settings.description)
$sanitize just sanitize the html but we are allowing support for markdown here and reference taken from here
[https://github.com/Source-Digital/marketplace-admin/blob/d2c951c3c5548a5be45fea0451d48ba7a84b8188/src/components/SmartBlocks/Markdown.vue#L42](SmartBlocks/Markdown.vue)

2021-02-11 14:55 UTC, sonokoh commented on src/components/SmartBlocks/Brand.vue
> +        this.$ee.templates.html.escape(this.settings.description)
Okay thanks for the info. Can you verify that this is not vulnerable to XSS? (both HTML and Markdown XSS)
FYI `$sanitize` takes options as a second argument and can be customized. https://github.com/markedjs/marked/issues/1388#issuecomment-447048317

2021-02-16 14:44 UTC, onexdata approved these changes

2021-02-16 15:32 UTC, sonokoh requested changes
Hi, few more minor changes requested. Ty for the fixes!

2021-02-16 15:32 UTC, sonokoh commented on src/components/SmartBlocks/Editor/BrandEditor.vue
> +    sanitizeInputs (obj, slug, inset) {
Looks like this `sanitizeInput` func is not used, and it uses recursive code which seems broken. Can we remove this?

2021-02-16 15:32 UTC, sonokoh commented on src/components/Maps.vue
> +        console.log(err)
Use console.error for error logging please. no console log rule applies.

2021-02-17 15:08 UTC, sonokoh approved these changes
Thanks for the fixes!

2021-02-17 15:09 UTC, merged