Smartblocks | Lib | Extractions
Source-Digital/marketplace-admin pull request #70
Opened 2021-02-10 19:58 UTC by c-49

Task: https://app.asana.com/0/1147388120266478/1199922325977541

Blocks using dependencies and/or quasar components:
- SanitizeHtml: Ad, Markdown, Product
- SurveyMonkey: Survey
- Quasar: Action, Product

2021-02-11 14:39 UTC, sonokoh requested changes
Again thanks for the help! Added couple of review comments, please check. Thanks!

2021-02-11 14:39 UTC, sonokoh commented on src/components/SmartBlocks/Action.vue
> +  name: 'SmartBlockActionEditor',
Ty for renaming editor components as well!

2021-02-11 14:39 UTC, sonokoh commented on src/components/SmartBlocks/App.vue
> +        :url="url"
This url computation needs to happen inside the smartblock. In real world scenario we only pass `settings` prop to SmartBlock component and it will do all the work.
Would you pls refactor? Ty!

2021-02-11 14:39 UTC, sonokoh commented on src/components/SmartBlocks/Markdown.vue
> +      :html="html"
The same here, html should be computed inside the markdown.

2021-02-11 14:39 UTC, sonokoh commented on src/components/lib/smartblocks/SmartBlockApp.vue
> +    <div v-else>
I believe we never want to show such preview messages in production (EE), so would you extract this piece out of renderer components as well? The lighter the components the better.

2021-02-11 14:39 UTC, sonokoh commented on src/components/lib/smartblocks/SmartBlockSurvey.vue
> +const Survey = SurveyVue.Survey
Explicit import is always better, also it helps tree shaking as well. Would you test the suggestion below?
```suggestion
import { StylesManager, Survey } as SurveyVue from 'survey-vue'
import 'survey-vue/survey.css'
SurveyVue.StylesManager.applyTheme('default')
```

2021-02-11 14:39 UTC, sonokoh commented on src/components/lib/smartblocks/SmartBlockSurvey.vue
> +    settings: [Object, String]
Why is String allowed here? Can we remove it?

2021-02-11 14:39 UTC, sonokoh commented on src/components/lib/smartblocks/SmartBlockSurvey.vue
> +    var json = this.settings
let's always use `const/let` (may not be your code but pls help me clean when we can!) Can you make sure to run linter and remove all warnings and errors from files you've worked on?

2021-02-11 18:05 UTC, c-49 commented on src/components/lib/smartblocks/SmartBlockSurvey.vue
> +    settings: [Object, String]
I added String, because of this error:
![image](https://user-images.githubusercontent.com/47996128/107675773-07e36200-6c5e-11eb-8aae-9e619e6172f8.png)
That happens when entering a new survey object into the input. However, QInput stringifys the value, so I've switched input for a json editor.

2021-02-11 18:08 UTC, sonokoh commented on src/components/lib/smartblocks/SmartBlockSurvey.vue
> +    settings: [Object, String]
> QInput stringifys the value, so I've switched input for a json editor.
Sounds good to me, thanks! Lets make sure settings is always an object.

2021-02-12 17:40 UTC, sonokoh approved these changes
Thanks a lot for the help!

2021-02-12 17:40 UTC, merged